default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= Rails.application.credentials.rails_max_thread || 5 %>
  database: <%= Rails.application.credentials.database[:name] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:hostname] %>
  socket: <%= Rails.application.credentials.database[:socket] %>
  timeout: <%= Rails.application.credentials.database[:timeout] || 10000 %>

development:
  <<: *default

test:
  <<: *default
  database: <%= Rails.application.credentials.database[:name] %>_test

production:
  <<: *default

staging:
  <<: *default

