default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: example_db

test:
  <<: *default
  database: example_db_test

production:
  <<: *default
  database: example_production
  username: example
  password: <%= ENV['MONO_DATABASE_PASSWORD'] %>
